(async()=>{
	const mobileMenu = await import('/src_js/header/script.js')
	mobileMenu.initial()
	const formResearch = await import('/src_js/form_research/script.js')
	formResearch.initial()
	const formParticipate = await import('/src_js/form_participate/script.js')
	formParticipate.initial()
	const formContacts = await import('/src_js/form_contacts/script.js')
	formContacts.initial()
	const searchClinic = await import('/src_js/search_clinic/script.js')
	searchClinic.initial()
	const searchResearch = await import('/src_js/search_research/script.js?v=1')
	searchResearch.initial()
	const searchDoctors = await import('/src_js/search_doctors/script.js')
	searchDoctors.initial()
	const formSubscription = await import('/src_js/form_subscription/script.js')
	formSubscription.initial()
	const formSubscriptionMain = await import('/src_js/form_subscription_main/script.js')
	formSubscriptionMain.initial()
	const formAnalyzes = await import('/src_js/form_analyzes/script.js?v=1')
	formAnalyzes.initial()
	const cookies = await import('/src_js/cookies/script.js')
	cookies.initial()
	const storiesDownload = await import('/src_js/stories_download/script.js')
	storiesDownload.initial()
	const searchHealing = await import('/src_js/search_healing/script.js')
	searchHealing.initial()
})()