<?php
$this->load->view('components/head/head.php');
$this->load->view('components/header/header.php');
$this->load->view('components/research_single/index.php');
$this->load->view('components/research_button/index.php');
$this->load->view('components/research_relative_clinic/index.php');
$this->load->view('components/relative_research_title/index.php');
$this->load->view('components/research_loop/index.php');
$this->load->view('components/footer/index.php');